server:
  port: 31000
  servlet:
    context-path: /employee-assignment/

spring:
  datasource:
    # rewriteBatchedStatements=true是mysql批量处理配置
    url: jdbc:mysql://172.20.112.33:3306/employee_assignment?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8&useSSL=false&rewriteBatchedStatements=true
    username: employee_assigner
    password: allocateJobs-2022
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 200
      minimum-idle: 20
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 1000MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    #控制台打印LOG，带SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/com/sw/basis/mapper/xml/*.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0