spring:
  profiles:
    active: dev
  messages:
    encoding: UTF-8
  jackson:
    serialization:
      write-dates-as-timestamps: true
  devtools:
    restart:
      enabled: false
  boot:
    admin:
      client:
        url: http://localhost:9090